### ISSUE TITLE
Nested object + nested form declaration breaks validation 

### ISSUE THREAD

**Issue by Bnaya** [networknt/react-schema-form#13] opened 2016-03-10 14:23 UTC
How to repro:
On the live demo:
http://networknt.github.io/react-schema-form/
select the object example

paste this form:
Form:
```
[
  "name",
  {
    "key": "attributes",
    "items": [
        {
            "title": "haircolor",
            "key": "haircolor",
            "type": "text"
        }
    ]
  }
]
```

Open the browser console, start typing text in the haircolor filed.
You will get js errors:
```
Uncaught TypeError: Cannot read property 'type' of undefined
```

On the original source the error comes from:
```
    onChangeValidate(e) {
        //console.log('onChangeValidate e', e);
        let value = null;
        if (this.props.form.schema.type === 'integer' || this.props.form.schema.type === 'number') {
```

After some debug my conclusions are:
The utils.merge function augmenting the form nodes with the proper scheme data node
when it gets nested object + form its need to recurse to do her job, but in some point it using undefined scheme data.

**Comment by nicklasb** [comment] 2016-03-10 14:40
It is correct to display that error, the reference is invalid.

Instead use 
```
  {
    "key": "attributes.haircolor"
  }
```
to address that property. 

The items construct is for arrays, fieldsets and similar: https://github.com/json-schema-form/json-schema-form/wiki/Documentation#array

**Comment by nicklasb** [comment] 2016-03-10 14:41
I see that the documentation needs to be improved, the examples for the array type is far to complex.

**Comment by Bnaya** [comment] 2016-03-10 14:50
Thanks!
how i should add attributes title group for this?

**Comment by nicklasb** [comment] 2016-03-10 15:07
What do you mean with title group? There are several json-schema-form concepts that could sort of be called a "Title group". Do you mean a section?

**Comment by Bnaya** [comment] 2016-03-10 15:10
Ok i did something like that:
```
[
    {
        title: 'Font info',
        key: 'metadata',
        type: 'fieldset',
        items: [],
        description: 'description: font info'
    },
    {
        key: 'metadata.family',
        type: 'text',
        title: 'Family',
        description: 'We should include the font weight in the name, and keep weight as normal.',
        default: ''
    },
    {
        key: 'metadata.stretch',
        type: 'text',
        title: 'Stretch',
        default: 'normal'
    },
    {
        key: 'metadata.weight',
        type: 'text',
        title: 'Weight',
        default: 'normal'
    },
    {
        key: 'metadata.style',
        type: 'text',
        title: 'Style',
        default: 'normal'
    }
]
```
The metadata with items [] gives me title to that group of inputs
Is there some more elegant solution

**Comment by nicklasb** [comment] 2016-03-10 15:13
Haven't tested it, but something like this?

[
    {
        title: 'Font info',
        key: 'metadata',
        type: 'fieldset',
        items: [    {
        key: 'metadata.family',
        type: 'text',
        title: 'Family',
        description: 'We should include the font weight in the name, and keep weight as normal.',
        default: ''
    },
    {
        key: 'metadata.stretch',
        type: 'text',
        title: 'Stretch',
        default: 'normal'
    },
    {
        key: 'metadata.weight',
        type: 'text',
        title: 'Weight',
        default: 'normal'
    },
    {
        key: 'metadata.style',
        type: 'text',
        title: 'Style',
        default: 'normal'
    }
],
        description: 'description: font info'
    },

]

**Comment by Bnaya** [comment] 2016-03-10 15:55
Thanks!
looks like its working, ill keep updating this issue until i will be sure.
```ts
const form: Array<any> = [
    {
        key: 'resourceRef',
    },
    {
        title: 'Font info',
        key: 'metadata',
        type: 'fieldset',
        items: [
            {
                key: 'metadata.family',
                type: 'text',
                title: 'Family',
                description: 'We should include the font weight in the name, and keep weight as normal.',
                default: ''
            },
            {
                key: 'metadata.stretch',
                type: 'text',
                title: 'Stretch',
                default: 'normal'
            },
            {
                key: 'metadata.weight',
                type: 'text',
                title: 'Weight',
                default: 'normal'
            },
            {
                key: 'metadata.style',
                type: 'text',
                title: 'Style',
                default: 'normal'
            }
        ],
        description: 'description: font info'
    }
];

export default form;
```

**Comment by nicklasb** [comment] 2016-03-10 17:00
I can't speak for @stevehu, but I would prefer that you close the issue as not only your question, but another question has been answered.

An issue is resolved when the issue is resolved, it is not an ongoing communication. 
I'd say that is a bit too much to expect from a non-commercial open source project,

**Comment by Bnaya** [comment] 2016-03-10 17:01
Got your point, I can still use this issue even if it closed

**Closed** 2016-03-10 17:01 UTC

**Comment by nicklasb** [comment] 2016-03-10 17:04
You may do as you which, but try to create one issue per problem, then it is more searchable/usable for others.
